version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_resume
    ports:
      - "${MINIO_API_PORT}:9000"     # MinIO API port
      - "${MINIO_CONSOLE_PORT}:9001" # MinIO Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data:
