version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai_resume_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:postgres}
      POSTGRES_USER: ${POSTGRES_USER:sfn}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:sfn123}
    ports:
      - "${POSTGRES_PORT:5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: